#ifndef FLUID_H
#define FLUID_H

#include "Material.h"

class Fluid: public Material{
public:
    float Heat(float Volume, float dT) const final; // Heating liquid with given volume
    float Pressure(float Height) const; // Pressure generated by a column of liquid with given height
    float GetMass(float Radius) const override; // Mass of orb with given radius
    void ChangeDensity(float delta) override; // Changes no more than 1
};

#endif
