#ifndef FLUID_H
#define FLUID_H

#include "Material.h"

class Fluid: public Material{
public:
    float Heat(float Volume, float dT); // Heating liquid with given volume
    float Pressure(float Height); // Pressure generated by a column of liquid with given height
};

#endif
